services:
  umbrella-backend:
    build: ./backend
    container_name: umbrella-backend
    ports:
      - 8080:8080

  umbrella-frontend:
    build: ./frontend
    container_name: umbrella-frontend
    ports:
      - 4200:4200
    links:
      - umbrella-backend
